apiVersion: v1
kind: Service
metadata:
  name: udp-service
spec:
  type: NodePort
  selector:
    app: udp-server
  ports:
    - port: 30010
      targetPort: 30007
      nodePort: 30011
      protocol: UDP